### ISSUE TITLE
Yolo v4 support

### ISSUE THREAD

**Issue by loretoparisi** [emadboctorx/yolov3-keras-tf2#1]
Is it on the roadmap? 
Thank you.

**Comment by emadboctorx** [comment]
Yes, I'm working on adding yolov4 configuration as well as a few other things, check the TODO list in the README

**Comment by emadboctorx** [comment]
@loretoparisi V4 is currently available check the v4 branch, I'm testing it currently and I will merge and update the README and everything else when the code is ready

**Comment by emadboctorx** [comment]
Yolov4 is currently available in master, supports training, inference ...
